Fixed bug: now selects first favorite item, on arrow key switch
humdingerb/clipdinger pull request #28
Opened 2019-12-12 20:09 UTC by R4H33M

Fixes #23 
Replicated and fixed. Switching between the favorite list and clips list is more consistent now.

2019-12-12 22:05 UTC, emily0618 commented
Hmm, I can't reproduce the bug...

2019-12-13 06:16 UTC, humdingerb commented
This doesn't fix the real issue.  It doesn't matter how many items are in the favourites list, if no item was selected before, none will be selected when the FavView gets focus.
My suggestion: Whenever the FavView gets focus, select the first item if none is currrently selected.

2019-12-13 08:45 UTC, R4H33M commented
There. I've implemented it exactly as suggested. Works well.
What do you say?

2019-12-13 08:51 UTC, humdingerb commented
But what happens if the user hits the tab key to change the focus instead of the right cursor key? :)

2019-12-13 09:00 UTC, R4H33M commented
Totally forgot about that. Thanks! Now it should work in all cases!

2019-12-13 11:38 UTC, humdingerb requested changes

2019-12-13 11:39 UTC, humdingerb commented on FavView.cpp
> +	if (focused){
Also tiny code style violation, space between round and curlies. :)

2019-12-13 15:58 UTC, R4H33M commented on FavView.cpp
> +			BListView::Select(0);
Good question... Actually I have no idea, I'm still learning C++
Since it works both ways, let's go for the more concise method.

2019-12-13 16:00 UTC, R4H33M commented
Ready for review!

2019-12-13 16:32 UTC, humdingerb requested changes

2019-12-13 16:32 UTC, humdingerb commented on FavView.cpp
> +
Remove the duplicate empty line.

2019-12-13 16:32 UTC, humdingerb commented on FavView.cpp
> +
Remove the two tabs in the empty line.

2019-12-13 18:31 UTC, humdingerb approved these changes

2019-12-13 18:34 UTC, merged